### ISSUE TITLE
Request - Gradle

### ISSUE THREAD

**Issue by TurKurT656** [navasmdc/PhoneTutorial#2]
Wish To Use This Great Lib With Gradle.

Thnx :)

**Comment by navasmdc** [comment]
Hi, it already is in the JCenter reposirory, I haven't published the yet because I'm trying the library by gradle dependency. I'll upload a new version this night with the gradle information

**Comment by navasmdc** [comment]
Hi, you can use this library with gradle now!

**Comment by TurKurT656** [comment]
Thnx Bro :) 
I Love Ur Material Design Library Too :+1:
